package catalyst::Model::Root;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'catalyst::SchemaClass',
    
    connect_info => {
        dsn => 'dbi:mysql:DATABASE',
        user => 'USER',
        password => 'PASSWORD',
        mysql_enable_utf8 => 1
        
    }
);

=head1 NAME

catalyst::Model::Root - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<catalyst>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<catalyst::SchemaClass>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.63

=head1 AUTHOR

root

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
